# Generated by Django 3.2.23 on 2023-12-06 19:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PncGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(blank=True, default='', max_length=30, verbose_name='Stato')),
                ('datacreazione', models.DateField(default=datetime.date.today, verbose_name='Data di inserimento')),
            ],
            options={
                'verbose_name': 'Prima nota contabile',
                'verbose_name_plural': 'Prime Note Contabili',
            },
        ),
        migrations.CreateModel(
            name='ContoCOGE',
            fields=[
                ('idContoCOGE', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=2)),
                ('descrizione', models.CharField(max_length=20, verbose_name='Descrizione')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='contable.contocoge')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
