# Generated by Django 3.2.23 on 2023-12-10 00:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anag_utenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContoCOGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=2)),
                ('descrizione', models.CharField(default='', max_length=50, verbose_name='Descrizione')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='contable.contocoge')),
            ],
            options={
                'verbose_name': 'Conto',
                'verbose_name_plural': 'Conti',
            },
        ),
        migrations.CreateModel(
            name='PncGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCreazionePnc', models.DateField(default=datetime.date.today, editable=False, verbose_name='Data di Creazione')),
                ('numPnc', models.CharField(blank=True, default='', max_length=10, verbose_name='Numero Nota')),
                ('dataPnc', models.DateField(default=datetime.date.today, verbose_name='Data del documento')),
                ('esercizioCompetenza', models.CharField(default='2023', max_length=4, verbose_name='Esercizio Contabile')),
                ('causalePnC', models.CharField(blank=True, default='', max_length=50, verbose_name='Causale')),
            ],
            options={
                'verbose_name': 'Prima Nota Contabile',
                'verbose_name_plural': 'Prime Note Contabili',
            },
        ),
        migrations.CreateModel(
            name='PncTes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TipiDocCoge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codDoc', models.CharField(default='', max_length=4, verbose_name='Codice Documento')),
                ('DesDoc', models.CharField(max_length=30, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Tipo di Documento di contabilità',
                'verbose_name_plural': 'Tipi di Documento di contabilità',
            },
        ),
        migrations.CreateModel(
            name='PncRighe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRiga', models.CharField(blank=True, default='', max_length=10, verbose_name='ID')),
                ('descrizioneRiga', models.CharField(default='', max_length=50, verbose_name='Descrizione')),
                ('dare', models.DecimalField(blank=True, decimal_places=5, max_digits=16, null=True)),
                ('avere', models.DecimalField(blank=True, decimal_places=5, max_digits=16, null=True)),
                ('competenzaDa', models.DateField(default=datetime.date.today, verbose_name='Competenza da')),
                ('competenzaA', models.DateField(default=datetime.datetime(2099, 12, 31, 0, 0), verbose_name='Competenza A')),
                ('conto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contable.contocoge')),
                ('idPnc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contable.pncgen')),
                ('partitarioRiga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anag_utenti.anagraficautenti')),
            ],
            options={
                'verbose_name': 'Riga',
                'verbose_name_plural': 'Righe',
            },
        ),
        migrations.AddField(
            model_name='pncgen',
            name='tipoDoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contable.tipidoccoge'),
        ),
    ]
