"""
Django settings for public_python project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _
from django.conf import settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#consente l'apertura di popup nello stesso dominio, evitando il blocco per il clickjacking
SECURE_FRAME_DENY = False
SECURE_CONTENT_TYPE_DENY = False
X_FRAME_OPTIONS = 'SAMEORIGIN'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gm5q(q6s2821e*x(d=ws6+3=zuql6l2-cfd767vzjgkdj6wp*&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if DEBUG:
    ALLOWED_HOSTS = ['127.0.0.1','localhost']
else:
    ALLOWED_HOSTS = ['bleish.serv00.net']


# Application definition

INSTALLED_APPS = [
    'organizations',
    'multigroup',
    'admin_interface',
    'colorfield',
    'anag_utenti.apps.AnagUtentiConfig',
    'contable.apps.ContableConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'info.apps.InfoConfig',
    'mptt',
    'django_mptt_admin',
    'stdForm',
    'bootstrap_modal_forms',
    
]

if settings.DEBUG:
    INSTALLED_APPS += ["debug_toolbar",]
    INTERNAL_IPS = [
        "127.0.0.1",
    ]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'multigroup.middleware.GruppoMiddleware',
]
if settings.DEBUG:
    MIDDLEWARE = ["debug_toolbar.middleware.DebugToolbarMiddleware",]+MIDDLEWARE



ROOT_URLCONF = 'public_python.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "public_python/templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'multigroup.context_processors.custom_context'
            ],
        },
    },
]

WSGI_APPLICATION = 'public_python.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            #'ENGINE': 'django.db.backends.mysql',
            #'NAME': 'm9800_agricontable',
            #'USER': 'm9800_bleish',
            #'PASSWORD': 'gioio,io@SERV00',
            #'HOST':'mysql4.serv00.com',
            #'PORT':'3306',
            #'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",}
        }
    }
else:
    DATABASES = {
        'default': {
            #'ENGINE': 'django.db.backends.sqlite3',
            #'NAME': BASE_DIR / 'db.sqlite3',
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'm9800_agricontable',
            'USER': 'm9800_bleish',
            'PASSWORD': 'gioio,io@SERV00',
            'HOST':'mysql4.serv00.com',
            'PORT':'3306',
            'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",}
        }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'it-it'

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('it', _('Italian')),
    ('en', _('English')),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
# https://docs.djangoproject.com/it/5.1/howto/static-files/deployment/
# https://docs.djangoproject.com/it/5.1/howto/deployment/wsgi/modwsgi/#serving-files

# Come per i template, per fare in modo che Django punti sul file corretto, occorre inserirlo in un namespace,
# ovvero inserendolo dentro un’altra directory che abbia come nome 
# il nome della app stessa: my_prog/static/app_del_progetto

#STATIC_URL = 'static/'
STATIC_URL = 'static/'
MEDIA_URL = 'media/'

# Quando gli asset statici che non sono legati ad una app particolare, oltre ad usare una directory static/ 
# si può definire una lista di directory (STATICFILES_DIRS) dove Django cercherà ulteriormente i file statici.
# Valorizzata STATICFILES_DIRS occorre eseguire collestatic
#STATICFILES_DIRS =  (os.path.join(BASE_DIR, 'assets'),)


STATIC_ROOT = os.path.join(BASE_DIR, 'public', 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'public', 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#############################################################################à
# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Replace with your SMTP host
EMAIL_HOST_USER = "gellebedde@gmail.com"  # Your email address
EMAIL_HOST_PASSWORD = "your host password"  # Your email password
EMAIL_PORT = 465  # SMTP port
EMAIL_USE_SSL = True  # Use SSL for secure connection
