# Generated by Django 3.2.23 on 2023-11-26 22:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieUtente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiceCategoriaUtente', models.CharField(max_length=10, verbose_name='Categoria Utente')),
                ('descrizioneCategoriaUtente', models.CharField(max_length=30, verbose_name='Descrizione')),
                ('noteCategoriaUtente', models.CharField(max_length=50, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='TipiUtente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiceTipoUtente', models.CharField(max_length=10, verbose_name='Tipo Utente')),
                ('descrizioneTipoUtente', models.CharField(max_length=30, verbose_name='Descrizione')),
                ('noteTipoUtente', models.CharField(max_length=50, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='AnagraficaUtenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.IntegerField(verbose_name='Codice')),
                ('cognome', models.CharField(max_length=50, verbose_name='Ragione sociale/Cognome')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cf', models.CharField(max_length=20, verbose_name='C.F.')),
                ('pec', models.CharField(max_length=50, verbose_name='Pec')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('cell', models.CharField(max_length=20, verbose_name='Cellulare')),
                ('tel', models.CharField(max_length=20, verbose_name='Telefono fisso')),
                ('sdi', models.CharField(max_length=10, verbose_name='Codice Univoco SDI')),
                ('note', models.CharField(max_length=250, verbose_name='Note')),
                ('iban', models.CharField(max_length=30, verbose_name='IBAN')),
                ('indirizzo', models.CharField(max_length=50, verbose_name='Indirizzo')),
                ('cap', models.CharField(max_length=6, verbose_name='C.A.P.')),
                ('citta', models.CharField(max_length=20, verbose_name='Città')),
                ('prov', models.CharField(max_length=3, verbose_name='Prov')),
                ('stato', models.CharField(max_length=20, verbose_name='Stato')),
                ('dataNascita', models.DateTimeField(verbose_name='Data di nascita')),
                ('luogoNascita', models.CharField(max_length=20, verbose_name='Luogo di Nascita')),
                ('datacreazione', models.DateTimeField(default=datetime.date.today, verbose_name='Data di inserimento')),
                ('categoriaUtente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anag_utenti.categorieutente')),
                ('tipoUtente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anag_utenti.tipiutente')),
            ],
        ),
    ]
