# Generated by Django 3.2.23 on 2023-12-09 12:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnagColtura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiceTipoColtura', models.CharField(max_length=10, verbose_name='Codice Tipo Coltura')),
                ('DescrColtura', models.CharField(max_length=30, verbose_name='Descrizione')),
                ('NoteColtura', models.CharField(blank=True, max_length=50, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Anagrafica Colture',
                'verbose_name_plural': 'Anagrafiche Colture',
            },
        ),
        migrations.CreateModel(
            name='CategorieUtente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiceCategoriaUtente', models.CharField(max_length=10, verbose_name='Categoria Utente')),
                ('descrizioneCategoriaUtente', models.CharField(max_length=30, verbose_name='Descrizione')),
                ('noteCategoriaUtente', models.CharField(blank=True, max_length=50, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Categoria Utente',
                'verbose_name_plural': 'Categorie Utenti',
            },
        ),
        migrations.CreateModel(
            name='TipiUtente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiceTipoUtente', models.CharField(max_length=10, verbose_name='Tipo Utente')),
                ('descrizioneTipoUtente', models.CharField(max_length=30, verbose_name='Descrizione')),
                ('noteTipoUtente', models.CharField(blank=True, max_length=50, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Tipo Utente',
                'verbose_name_plural': 'Tipi Utenti',
            },
        ),
        migrations.CreateModel(
            name='AnagraficaUtenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.IntegerField(verbose_name='Codice')),
                ('cognome', models.CharField(max_length=50, verbose_name='Ragione sociale/Cognome')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('dataNascita', models.DateField(verbose_name='Data di nascita')),
                ('luogodinascita', models.CharField(default='', max_length=30, verbose_name='Luogo di nascita')),
                ('cf', models.CharField(blank=True, max_length=16, verbose_name='Codice Fiscale')),
                ('piva', models.CharField(blank=True, default='', max_length=25, verbose_name='P.IVA')),
                ('email', models.CharField(blank=True, default='', max_length=50, verbose_name='email')),
                ('pec', models.CharField(blank=True, default='', max_length=50, verbose_name='pec')),
                ('tel', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefono')),
                ('cell', models.CharField(blank=True, default='', max_length=20, verbose_name='Cellulare')),
                ('sdi', models.CharField(blank=True, default='', max_length=10, verbose_name='Codice Univoco SDI')),
                ('iban', models.CharField(blank=True, default='', max_length=30, verbose_name='IBAN')),
                ('indirizzo', models.CharField(blank=True, default='', max_length=50, verbose_name='Indirizzo')),
                ('cap', models.CharField(blank=True, default='', max_length=6, verbose_name='CAP')),
                ('citta', models.CharField(blank=True, default='', max_length=30, verbose_name='Città')),
                ('prov', models.CharField(blank=True, default='', max_length=30, verbose_name='Prov')),
                ('stato', models.CharField(blank=True, default='', max_length=30, verbose_name='Stato')),
                ('datacreazione', models.DateField(default=datetime.date.today, verbose_name='Data di inserimento')),
                ('categoriaUtente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='anag_utenti.categorieutente')),
                ('tipoUtente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='anag_utenti.tipiutente')),
            ],
            options={
                'verbose_name': 'Anagrafica Utente',
                'verbose_name_plural': 'Anagrafiche Utenti',
            },
        ),
    ]
