# Generated by Django 3.2.23 on 2023-11-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anag_utenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnagColtura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiceTipoColtura', models.CharField(max_length=10, verbose_name='Codice Tipo Coltura')),
                ('DescrColtura', models.CharField(max_length=30, verbose_name='Descrizione')),
                ('NoteColtura', models.CharField(max_length=50, verbose_name='Note')),
            ],
        ),
        migrations.RemoveField(
            model_name='anagraficautenti',
            name='luogoNascita',
        ),
        migrations.RemoveField(
            model_name='anagraficautenti',
            name='note',
        ),
        migrations.AddField(
            model_name='anagraficautenti',
            name='luogodinascita',
            field=models.CharField(default='', max_length=30, verbose_name='Luogo di nascita'),
        ),
        migrations.AddField(
            model_name='anagraficautenti',
            name='piva',
            field=models.CharField(default='', max_length=25, verbose_name='P.IVA'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='cap',
            field=models.CharField(default='', max_length=6, verbose_name='CAP'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='cell',
            field=models.CharField(default='', max_length=20, verbose_name='Cellulare'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='cf',
            field=models.CharField(max_length=16, verbose_name='Codice Fiscale'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='citta',
            field=models.CharField(default='', max_length=30, verbose_name='Città'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='email',
            field=models.CharField(default='', max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='iban',
            field=models.CharField(default='', max_length=30, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='indirizzo',
            field=models.CharField(default='', max_length=50, verbose_name='Indirizzo'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='pec',
            field=models.CharField(default='', max_length=50, verbose_name='pec'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='prov',
            field=models.CharField(default='', max_length=30, verbose_name='Prov'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='sdi',
            field=models.CharField(default='', max_length=10, verbose_name='Codice Univoco SDI'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='stato',
            field=models.CharField(default='', max_length=30, verbose_name='Stato'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='tel',
            field=models.CharField(default='', max_length=20, verbose_name='Telefono'),
        ),
    ]
