# Generated by Django 3.2.23 on 2023-11-28 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anag_utenti', '0002_auto_20231127_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagcoltura',
            name='NoteColtura',
            field=models.CharField(blank=True, max_length=50, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='cap',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='CAP'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='categoriaUtente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='anag_utenti.categorieutente'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='cell',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cellulare'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='cf',
            field=models.CharField(blank=True, max_length=16, verbose_name='Codice Fiscale'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='citta',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Città'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='dataNascita',
            field=models.DateField(verbose_name='Data di nascita'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='datacreazione',
            field=models.DateField(default=datetime.date.today, verbose_name='Data di inserimento'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='indirizzo',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Indirizzo'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='pec',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='pec'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='piva',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='P.IVA'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='prov',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Prov'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='sdi',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Codice Univoco SDI'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='stato',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Stato'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='anagraficautenti',
            name='tipoUtente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='anag_utenti.tipiutente'),
        ),
        migrations.AlterField(
            model_name='categorieutente',
            name='noteCategoriaUtente',
            field=models.CharField(blank=True, max_length=50, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='tipiutente',
            name='noteTipoUtente',
            field=models.CharField(blank=True, max_length=50, verbose_name='Note'),
        ),
    ]
