# Generated by Django 3.2.23 on 2023-11-28 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anag_utenti', '0003_auto_20231128_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anagcoltura',
            options={'verbose_name': 'Anagrafica Colture', 'verbose_name_plural': 'Anagrafiche Colture'},
        ),
        migrations.AlterModelOptions(
            name='anagraficautenti',
            options={'verbose_name': 'Anagrafica Utente', 'verbose_name_plural': 'Anagrafiche Utenti'},
        ),
        migrations.AlterModelOptions(
            name='categorieutente',
            options={'verbose_name': 'Categoria Utente', 'verbose_name_plural': 'Categorie Utenti'},
        ),
        migrations.AlterModelOptions(
            name='tipiutente',
            options={'verbose_name': 'Tipo Utente', 'verbose_name_plural': 'Tipi Utenti'},
        ),
    ]
