# Generated by Django 3.2.23 on 2023-12-06 09:34

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anag_utenti', '0004_auto_20231128_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContoCOGE',
            fields=[
                ('idContoCOGE', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=2)),
                ('descrizione', models.CharField(max_length=20, verbose_name='Descrizione')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='anag_utenti.contocoge')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
