# Generated by Django 3.2.23 on 2023-12-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anag_utenti', '0005_contocoge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContoCOGE',
        ),
    ]
